language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.6.6
before_script:
  - mysql -e 'create database enju_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start
services:
  - redis-server
  - mysql
  - postgresql
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
matrix:
notifications:
  slack:
    secure: Z8IJxPCkgeKxx0vX8VJwtTUvayrKteo3IQFPvs5MPUaPP+Eu3Xc0mrcH5JqX/2VFG6PbWe1kCxFCci0q2y/ojHQ/OxoRA86jFMEmcn8qQ/q9HWRVQlY57PTWkPTVWi4sn0FGYkPUQ9JJy07TyxPmvAtdDpjl/pnGTJvDU/+3aUg=
sudo: false
jdk:
  - openjdk8
dist: xenial
