language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
before_script:
  - psql -c 'create database enju_manifestation_viewer_dummy_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
env:
  - DB=postgresql
matrix:
notifications:
  slack:
    secure: Z8IJxPCkgeKxx0vX8VJwtTUvayrKteo3IQFPvs5MPUaPP+Eu3Xc0mrcH5JqX/2VFG6PbWe1kCxFCci0q2y/ojHQ/OxoRA86jFMEmcn8qQ/q9HWRVQlY57PTWkPTVWi4sn0FGYkPUQ9JJy07TyxPmvAtdDpjl/pnGTJvDU/+3aUg=
sudo: false
